# Generated by Django 3.1.2 on 2020-11-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201110_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
    ]
